=== matkoniecz/test_manual_rerun/schemas/field.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/openstreetmap/id-tagging-schema/raw/main/schemas/field.json",
    "title": "Field",
    "description": "A reusable form element for presets",
    "type": "object",
    "properties": {
        "key": {
            "description": "Tag key whose value is to be displayed",
            "type": "string"
        },
        "keys": {
            "description": "Tag keys whose value is to be displayed",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "reference": {
            "description": "Taginfo documentation parameters (to be used when a field manages multiple tags)",
            "anyOf": [
                {
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "For documentation of a key",
                            "type": "string"
                        },
                        "value": {
                            "description": "For documentation of a tag (key and value)",
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key"]
                },
                {
                    "type": "object",
                    "properties": {
                        "rtype": {
                            "description": "For documentation of a relation type",
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["rtype"]
                }
            ]
        },
        "type": {
            "description": "Type of field",
            "type": "string",
            "enum": [
                "access",
                "address",
                "check",
                "colour",
                "combo",
                "date",
                "defaultCheck",
                "directionalCombo",
                "email",
                "identifier",
                "integer",
                "lanes",
                "localized",
                "manyCombo",
                "multiCombo",
                "networkCombo",
                "number",
                "onewayCheck",
                "radio",
                "restrictions",
                "roadheight",
                "roadspeed",
                "schedule",
                "semiCombo",
                "structureRadio",
                "tel",
                "text",
                "textarea",
                "typeCombo",
                "url",
                "wikidata",
                "wikipedia"
            ]
        },
        "label": {
            "description": "English label for the field caption. A field can reference the label of another by using that field's identifier contained in brackets (e.g. {field}), in which case also the field's terms will be referenced from that field.",
            "type": "string"
        },
        "geometry": {
            "description": "If specified, only show the field for these kinds of geometry",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
              "$ref": "#/$defs/Geometry"
            }
        },
        "default": {
            "description": "The default value for this field",
            "type": "string"
        },
        "options": {
            "description": "List of untranslatable string suggestions (combo fields)",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "autoSuggestions": {
            "description": "If true, the top values from TagInfo will be suggested in the dropdown (combo fields only)",
            "type": "boolean",
            "default": true
        },
        "customValues": {
            "description": "If true, the user can type their own value in addition to any listed in `options` or `strings.options` (combo fields only)",
            "type": "boolean",
            "default": true
        },
        "universal": {
            "description": "If true, this field will appear in the Add Field list for all presets",
            "type": "boolean",
            "default": false
        },
        "placeholder": {
            "description": "Placeholder text for this field. A field can reference the placeholder text of another by using that field's identifier contained in brackets, like {field}.",
            "type": "string"
        },
        "strings": {
            "description": "Strings sent to transifex for translation",
            "type": "object",
            "minProperties": 1,
            "additionalProperties": false,
            "properties": {
                "options": {
                    "description": "Translatable options (combo fields).",
                    "type": "object",
                    "minProperties": 1,
                    "additionalProperties": {
                        "oneOf": [
                            { "type": "string" },
                            {
                                "type": "object",
                                "properties": {
                                    "title": { "type": "string" },
                                    "description": { "type": "string" }
                                },
                                "required": ["title", "description"],
                                "additionalProperties": false
                            }
                        ]
                    }
                },
                "types": {
                    "description": "Translatable types (directionalCombo and access only).",
                    "type": "object",
                    "minProperties": 1,
                    "additionalProperties": { "type": "string" }
                },
                "placeholders": {
                    "description": "Translatable placeholders of fields with subfields (address only).",
                    "type": "object",
                    "minProperties": 1,
                    "additionalProperties": { "type": "string" }
                },
                "labels": {
                    "description": "Translatable labels of fields with subfields (address only).",
                    "type": "object",
                    "minProperties": 1,
                    "additionalProperties": { "type": "string" }
                }
            }
        },
        "stringsCrossReference": {
            "description": "A field can reference strings of another by using that field's identifier contained in brackets, like {field}.",
            "type": "string"
        },
        "snake_case": {
            "description": "If true, replace spaces with underscores in the tag value (combo fields only)",
            "type": "boolean",
            "default": true
        },
        "caseSensitive": {
            "description": "If true, allow case sensitive field values (combo fields only)",
            "type": "boolean",
            "default": false
        },
        "allowDuplicates": {
            "description": "If true, duplicate values are allowed (semiCombo fields only)",
            "type": "boolean",
            "default": false
        },
        "minValue": {
            "description": "Minimum field value (number fields only)",
            "type": "integer"
        },
        "maxValue": {
            "description": "Maximum field value (number fields only)",
            "type": "integer"
        },
        "increment": {
            "description": "The amount the stepper control should add or subtract (number fields only)",
            "minimum": 1,
            "type": "integer"
        },
        "prerequisiteTag": {
            "description": "Tagging constraint for showing this field in the editor",
            "oneOf": [
                {
                    "$id": "requires-key-any-value",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key"]
                },
                {
                    "$id": "requires-key-equals-value",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        },
                        "value": {
                            "description": "The value that the tag must have. (alternative to 'valueNot')",
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key", "value"]
                },
                {
                    "$id": "requires-key-equals-values",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        },
                        "values": {
                            "description": "The values that the tag must have. (alternative to 'valuesNot')",
                            "type": "array",
                            "items": { "type": "string" },
                            "minItems": 1
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key", "values"]
                },
                {
                    "$id": "requires-key-not-value",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        },
                        "valueNot": {
                            "description": "The value that the tag cannot have. (alternative to 'value')",
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key", "valueNot"]
                },
                {
                    "$id": "requires-key-not-values",
                    "type": "object",
                    "properties": {
                        "key": {
                            "description": "The key of the required tag",
                            "type": "string"
                        },
                        "valuesNot": {
                            "description": "The values that the tag cannot have. (alternative to 'values')",
                            "type": "array",
                            "items": { "type": "string" },
                            "minItems": 1
                        }
                    },
                    "additionalProperties": false,
                    "required": ["key", "valuesNot"]
                },
                {
                    "$id": "requires-not-key",
                    "type": "object",
                    "properties": {
                        "keyNot": {
                            "description": "A key that must not be present",
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["keyNot"]
                }
            ]
        },
        "terms": {
            "description": "English synonyms or related search terms",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "locationSet": {
            "description": "An object specifying the IDs of regions where this field is or isn't valid. See: https://github.com/ideditor/location-conflation",
            "type": "object",
            "minProperties": 1,
            "properties": {
                "include": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                },
                "exclude": {
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "string"
                    }
                }
            },
            "additionalProperties": false
        },
        "locationSetCrossReference": {
            "type": "string",
            "pattern": "^\\{.+\\}$",
            "description": "An string referencing another preset which has a locationSet"
        },
        "urlFormat":  {
            "description": "Permalink URL for `identifier` fields. Must contain a {value} placeholder",
            "type": "string"
        },
        "pattern":  {
            "description": "Regular expression that a valid `identifier` value is expected to match",
            "type": "string"
        },
        "usage": {
            "description": "The manner and context in which the field is used",
            "type": "string",
            "enum": ["preset", "changeset", "manual", "group"]
        },
        "icons": {
            "description": "For combo and radio fields: Name of icons which represents different values of this field",
            "type": "object",
            "minProperties": 1,
            "additionalProperties": {
                "type": "string"
            }
        },
        "iconsCrossReference": {
            "description": "A field can reference icons of another by using that field's identifier contained in brackets, like {field}.",
            "type": "string"
        }
    },
    "additionalProperties": false,
    "required": ["type", "label"],
    "anyOf": [
        { "$id": "field-type-without-key-nor-keys", "properties": { "type": { "enum": ["restrictions"] } }, "allOf": [
            { "not": { "required": ["key"] }},
            { "not": { "required": ["keys"] }}
        ]},
        { "$id": "field-type-with-key-optional-keys", "properties": { "type": { "enum": ["email", "url", "tel", "text", "number"] } }, "required": ["key"] },
        { "$id": "field-type-with-key-and-keys", "properties": { "type": { "enum": ["address", "wikipedia", "wikidata", "directionalCombo"] } }, "required": ["key", "keys"] },
        { "$id": "field-type-with-key-or-keys", "allOf": [
            { "not": { "properties": { "type": { "enum": ["restriction", "email", "url", "tel", "text", "number", "address", "wikipedia", "wikidata", "directionalCombo"] } } } },
            { "oneOf": [
                { "required": ["key"] },
                { "required": ["keys"] }
            ]}
        ]}
    ],
    "$defs": {
        "Geometry": {
            "type": "string",
            "enum": ["point", "vertex", "line", "area", "relation"]
        }
    }
}

=== matkoniecz/test_manual_rerun/data/fields/royal_cypher-GB.json
{
    "key": "royal_cypher",
    "type": "combo",
    "label": "Royal Cypher",
    "strings": {
        "options": {
            "VR": "VR (Victoria)",
            "EVIIR": "EVIIR (Edward VII)",
            "EVIIIR": "EVIIIR (Edward VIII)",
            "GR": "GR (George V)",
            "GVIR": "GVIR (George VI)",
            "EIIR": "EIIR (Elizabeth II)",
            "CIIIR": "CIIIR (Charles III)",
            "scottish_crown": "Scottish Crown",
            "no": "No"
        }
    },
    "autoSuggestions": false,
    "customValues": false,
    "locationSet": {
        "include": [
            "gb"
        ]
    }
}

=== matkoniecz/test_manual_rerun/data/fields/surface.json
{
    "key": "surface",
    "type": "combo",
    "label": "Surface",
    "strings": {
        "options": {
            "unpaved": "Unpaved",
            "paved": "Paved",
            "asphalt": "Asphalt",
            "concrete": "Concrete",
            "paving_stones": "Paving Stones",
            "ground": "Ground",
            "gravel": "Gravel",
            "dirt": "Dirt",
            "grass": "Grass",
            "compacted": "Compacted",
            "sand": "Sand",
            "sett": "Sett",
            "fine_gravel": "Fine Gravel",
            "wood": "Wood",
            "concrete:plates": "Concrete Plates",
            "pebblestone": "Pebblestone",
            "grass_paver": "Grass Paver",
            "metal": "Metal",
            "unhewn_cobblestone": "Cobblestone (uncut, rounded stones)",
            "concrete:lanes": "Concrete Lanes",
            "mud": "Persistently Muddy",
            "woodchips": "Woodchips",
            "salt": "Salt",
            "artificial_turf": "Artificial Turf",
            "tartan": "Tartan",
            "clay": "Clay"
        }
    }
}

=== matkoniecz/test_manual_rerun/data/fields/sport.json
{
    "key": "sport",
    "type": "semiCombo",
    "label": "Sports",
    "strings": {
        "options": {
            "soccer": "Soccer",
            "tennis": "Tennis",
            "basketball": "Basketball",
            "baseball": "Baseball",
            "multi": "Unspecified Other Sports",
            "equestrian": "Equestrian Sports",
            "swimming": "Swimming",
            "fitness": "Fitness Training",
            "athletics": "Track & Field",
            "running": "Running",
            "climbing": "Climbing",
            "table_tennis": "Table Tennis",
            "beachvolleyball": "Beach Volleyball",
            "golf": "Golf",
            "boules": "Boules",
            "volleyball": "Volleyball",
            "skateboard": "Skateboard",
            "pickleball": "Pickleball",
            "shooting": "Shooting",
            "motor": "Motorsports",
            "american_football": "American Football",
            "futsal": "Futsal",
            "cricket": "Cricket",
            "bowls": "Bowls",
            "padel": "Padel",
            "netball": "Netball",
            "cycling": "Cycling",
            "motocross": "Motocross",
            "karting": "Kart Racing",
            "badminton": "Badminton",
            "chess": "Chess",
            "softball": "Softball",
            "horse_racing": "Horse Racing",
            "rugby_union": "Rugby Union",
            "handball": "Team Handball",
            "yoga": "Yoga",
            "free_flying": "Paragliding / Hang Gliding",
            "gymnastics": "Gymnastics",
            "skiing": "Skiing",
            "ice_hockey": "Ice Hockey",
            "bmx": "BMX",
            "scuba_diving": "Scuba Diving",
            "pelota": "Pelota",
            "gaelic_games": "Gaelic Games",
            "disc_golf": "Disc Golf",
            "canoe": "Canoeing",
            "billiards": "Cue Sports",
            "10pin": "Ten-Pin Bowling",
            "ice_skating": "Ice Skating",
            "orienteering": "Orienteering",
            "9pin": "Nine-Pin Bowling",
            "ice_stock": "Ice Stock",
            "ski_jumping": "Ski Jumping",
            "curling": "Curling",
            "dog_racing": "Dog Racing",
            "darts": "Darts",
            "speedway": "Motorcycle Speedway",
            "candlepin": "Candlepin Bowling",
            "5pin": "Five-Pin Bowling",
            "duckpin": "Duckpin Bowling"
        }
    }
}

=== matkoniecz/test_manual_rerun/data/fields/hazard_highway.json
{
    "key": "hazard",
    "type": "combo",
    "strings": {
        "options": {
            "animal_crossing": "Animal Crossing",
            "children": "Children",
            "curve": "Curve",
            "school_zone": "School Zone",
            "landslide": "Landslide",
            "curves": "Multiple Curves",
            "dangerous_junction": "Dangerous Junction",
            "pedestrians": "Pedestrians",
            "cyclists": "Cyclists",
            "slippery": "Slippery",
            "falling_rocks": "Falling Rocks",
            "bump": "Bump",
            "turn": "Turn",
            "queues_likely": "Stopped Traffic",
            "ice": "Ice",
            "side_winds": "Side Winds",
            "turns": "Multiple Turns",
            "low_flying_aircraft": "Low Flying Aircraft",
            "dip": "Dip",
            "horse_riders": "Horse Riders",
            "loose_gravel": "Loose Gravel",
            "frost_heave": "Frost Heave"
        }
    },
    "label": "Signed Hazard"
}

=== matkoniecz/test_manual_rerun/data/fields/education.json
{
    "key": "education",
    "type": "typeCombo",
    "label": "Type",
    "strings": {
        "options": {
            "school": "School",
            "kindergarten": "Kindergarten",
            "university": "University",
            "college": "College",
            "driving_school": "Driving School",
            "language_school": "Language School",
            "music_school": "Music School",
            "prep_school": "Test Prep / Tutoring School",
            "dancing_school": "Dancing School"
        }
    }
}

=== matkoniecz/test_manual_rerun/data/fields/address.json
{
    "type": "address",
    "key": "addr",
    "reference": {
        "key": "addr:*"
    },
    "keys": [
        "addr:block_number",
        "addr:city",
        "addr:conscriptionnumber",
        "addr:country",
        "addr:county",
        "addr:district",
        "addr:door",
        "addr:floor",
        "addr:hamlet",
        "addr:housename",
        "addr:housenumber",
        "addr:neighbourhood",
        "addr:place",
        "addr:postcode",
        "addr:province",
        "addr:quarter",
        "addr:state",
        "addr:street",
        "addr:subdistrict",
        "addr:suburb",
        "addr:town",
        "addr:unit"
    ],
    "label": "Address",
    "strings": {
        "labels": {
            "conscriptionnumber": "Conscription Number",
            "housenumber": "House Number"
        },
        "placeholders": {
            "block_number": "Block Number",
            "block_number!jp": "Block No.",
            "city": "City",
            "city!cn": "City/Prefecture/League",
            "city!jp": "City/Town/Village/Tokyo Special Ward",
            "city!vn": "City/Town",
            "conscriptionnumber": "123",
            "country": "Country",
            "county": "County",
            "county!jp": "District",
            "district": "District",
            "district!cn": "District/County/Banner",
            "district!vn": "Arrondissement/Town/District",
            "door": "Door Number",
            "floor": "Floor",
            "hamlet": "Hamlet",
            "housename": "Housename",
            "housenumber": "123",
            "housenumber!jp": "Building No./Lot No.",
            "neighbourhood": "Neighborhood",
            "neighbourhood!jp": "Machi/Chōme/Aza/Koaza",
            "place": "Place",
            "postcode": "Postcode",
            "province": "Province",
            "province!cn": "Province/Municipality/AR/SAR",
            "province!jp": "Prefecture",
            "quarter": "Quarter",
            "quarter!jp": "Ōaza",
            "state": "State",
            "street": "Street",
            "subdistrict": "Subdistrict",
            "subdistrict!vn": "Ward/Commune/Townlet",
            "suburb": "Suburb",
            "suburb!jp": "Ward (政令市)",
            "town": "Town",
            "unit": "Unit"
        }
    },
    "terms": [
        "location"
    ]
}

=== matkoniecz/test_manual_rerun/data/fields/telescope/type.json
{
    "key": "telescope:type",
    "type": "combo",
    "label": "Type",
    "strings": {
        "options": {
            "optical": "Optical Telescope",
            "radio": "Radio Telescope"
        }
    },
    "icons": {
        "optical": "temaki-telescope",
        "radio": "roentgen-telescope_radio"
    },
    "autoSuggestions": true,
    "customValues": true
}

=== matkoniecz/test_manual_rerun/data/fields/generator/method/hydro.json
{
    "key": "generator:method",
    "type": "radio",
    "label": "{generator/method}",
    "stringsCrossReference": "{generator/method}",
    "options": [
        "water-storage",
        "water-pumped-storage",
        "run-of-the-river"
    ],
    "prerequisiteTag": {
        "key": "generator:source",
        "value": "hydro"
    }
}
